#!/usr/bin/env python3
"""bin -> ROM images: a $readmemh hex and a Verilog include (rom_init.vh).

The include is what synthesis consumes - committed next to the RTL, it
makes the ROM contents flow-independent: no parameter plumbing, no
chparam, no working-directory games. Usage: rom_gen.py fw.bin rom.hex
[rom_init.vh]."""
import sys

data = open(sys.argv[1], "rb").read()
assert len(data) <= 1024, f"firmware is {len(data)} bytes, ROM holds 1024"
used = len(data)
data += b"\x00" * (1024 - len(data))
words = [int.from_bytes(data[i:i+4], "little") for i in range(0, 1024, 4)]
with open(sys.argv[2], "w") as f:
    for w in words:
        f.write(f"{w:08x}\n")
if len(sys.argv) > 3:
    with open(sys.argv[3], "w") as f:
        f.write("// GENERATED by fw/rom_gen.py from fw/build/fw.bin - do not edit.\n")
        for i, w in enumerate(words):
            f.write(f"mem[{i}] = 32'h{w:08x};\n")
print(f"rom image: {used}/1024 bytes used")
