#!/usr/bin/env python3
# =============================================================================
# ZIRH - the ECSS-shaped compliance matrix generator (PROGRAM.md D16)
#
#   python3 scripts/evidence_matrix.py > docs/COMPLIANCE-MATRIX.md
#   python3 scripts/evidence_matrix.py --check     (CI: regenerate + diff)
#
# The pilot the brief asked for: fill the evidence-pack shape from a
# REAL project's requirements, not a blank template. It reads
# requirements.yaml (the same single source trace_check enforces) and
# renders the requirement -> verification-method -> evidence-artifact
# matrix in the shape an ECSS-Q-ST-60/DO-254 reviewer reads, with the
# verification method inferred from where each requirement's evidence
# lives:
#
#   formal/*.sv           -> Formal Proof
#   scripts/*.sh|.py      -> Analysis / Tool
#   test/*.py|.v          -> Test (simulation)
#   docs/*                -> Review / Inspection
#
# What makes this a PILOT and not a template: every row cites an
# artifact that exists and runs in CI today. The gap between "we have
# templates" and "we have a filled, defensible pack" is exactly this
# file, and it stays true automatically because it regenerates from
# the same YAML the build already gates.
# =============================================================================

import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent


def parse_reqs(text):
    reqs = []
    cur = None
    field = None
    for line in text.splitlines():
        m = re.match(r"  - id: (\S+)", line)
        if m:
            cur = {"id": m.group(1), "text": "", "tests": [], "evidence": ""}
            reqs.append(cur)
            field = None
            continue
        if cur is None:
            continue
        if re.match(r"\s+text:\s*(.*)", line):
            cur["text"] = re.match(r"\s+text:\s*(.*)", line).group(1).strip()
            field = "text"
        elif re.match(r"\s+tests:\s*$", line):
            field = "tests"
        elif re.match(r"\s+evidence:\s*(.*)", line):
            cur["evidence"] = re.match(r"\s+evidence:\s*(.*)", line).group(1).strip()
            field = "evidence"
        elif field == "tests" and re.match(r"\s+- (\S+)", line):
            cur["tests"].append(re.match(r"\s+- (\S+)", line).group(1))
        elif field == "text" and re.match(r"\s{6,}\S", line):
            cur["text"] += " " + line.strip()
        elif field == "evidence" and re.match(r"\s{6,}\S", line):
            cur["evidence"] += " " + line.strip()
    return reqs


def method(tests):
    kinds = set()
    for t in tests:
        if t.startswith("formal/"):
            kinds.add("Formal Proof")
        elif t.startswith("scripts/") or t.startswith("tmr-guard/"):
            kinds.add("Analysis/Tool")
        elif t.startswith("test/"):
            kinds.add("Test")
        elif t.startswith("docs/") or t.startswith("regmap") \
                or t.startswith("host/") or t.startswith("src/") \
                or t.startswith("fw/"):
            kinds.add("Review/Inspection")
    order = ["Formal Proof", "Test", "Analysis/Tool", "Review/Inspection"]
    return " + ".join(k for k in order if k in kinds) or "Review/Inspection"


def render(reqs):
    out = []
    out.append("# ZIRH-2 compliance matrix (ECSS-shaped pilot)")
    out.append("")
    out.append("GENERATED by scripts/evidence_matrix.py from "
               "requirements.yaml - the D16 pilot: the evidence-pack "
               "shape filled from a real project's requirements, every "
               "row citing an artifact that runs in CI today. "
               "Verification method is inferred from where each "
               "requirement's evidence lives. Regenerated and diffed in "
               "CI, so the matrix cannot drift from the requirements the "
               "build already gates.")
    out.append("")
    by_method = {}
    for r in reqs:
        by_method.setdefault(method(r["tests"]), []).append(r)
    out.append(f"**{len(reqs)} requirements** across "
               f"{len(by_method)} verification-method classes:")
    out.append("")
    for m in sorted(by_method, key=lambda k: -len(by_method[k])):
        out.append(f"- {m}: {len(by_method[m])}")
    out.append("")
    out.append("| ID | Requirement | Method | Verification artifacts | "
               "Evidence location |")
    out.append("|---|---|---|---|---|")
    for r in reqs:
        text = r["text"] if len(r["text"]) < 110 else r["text"][:107] + "..."
        arts = "<br>".join(f"`{t}`" for t in r["tests"])
        ev = r["evidence"] if len(r["evidence"]) < 120 \
            else r["evidence"][:117] + "..."
        out.append(f"| {r['id']} | {text} | {method(r['tests'])} "
                   f"| {arts} | {ev} |")
    out.append("")
    out.append("## Reviewer notes")
    out.append("")
    out.append("This matrix is the ECSS-Q-ST-60/DO-254-shaped view of "
               "the same requirements the build enforces via "
               "scripts/trace_check.py (no requirement without a test) "
               "and scripts/regmap_gen.py (no map drift). The formal "
               "rows are machine-checked theorems; the test rows run in "
               "the ci/test/formal/arch workflows on every push; the "
               "tool rows (tmr-guard, coverage, beam analysis) carry "
               "their own negative controls. The gap this pilot closes: "
               "a template proves nothing, a filled matrix that "
               "regenerates from the gated source proves the evidence "
               "chain is real and current.")
    return "\n".join(out) + "\n"


def main():
    reqs = parse_reqs((root / "requirements.yaml").read_text())
    md = render(reqs)
    if "--check" in sys.argv:
        path = root / "docs" / "COMPLIANCE-MATRIX.md"
        if not path.exists() or path.read_text() != md:
            print("FAIL: docs/COMPLIANCE-MATRIX.md is stale - run "
                  "scripts/evidence_matrix.py")
            sys.exit(1)
        print(f"compliance matrix: {len(reqs)} requirements, in sync")
        return
    sys.stdout.write(md)


if __name__ == "__main__":
    main()
