#!/usr/bin/env python3
# =============================================================================
# tmr-fsm-gen - emit a safe-state TMR FSM and the proof obligations with it
#
#   python3 scripts/tmr_fsm_gen.py spec.json -o my_fsm.v \
#       [--manifest-entry entry.json]
#
# The pattern ZIRH-2's CAN and SpaceWire engines proved under fault
# injection, as a generator: the FSM state lives in a voted-feedback TMR
# register (single-replica hits heal in one cycle and pulse err_o), and
# every UNREACHABLE state encoding falls into a designated recovery
# state through the case default - the pairing the fault-tolerant-FSM
# literature prescribes, and the one a double-replica hit needs.
#
# The generator's second output is the point: alongside the Verilog it
# emits the tmr-guard manifest entry with the EXPECTED replica and flop
# counts computed, not hand-maintained - the per-definition counting
# gotcha (same-width registers share one Yosys paramod definition) and
# the +1 err flop per register are encoded here once, so they stop
# being a thing humans get wrong per block.
#
# Spec (JSON):
#   {
#     "name": "my_link_fsm",
#     "states": ["IDLE", "SYNC", "RUN", "FLUSH"],
#     "recovery": "IDLE",
#     "transitions": [
#       {"from": "IDLE",  "when": "start_i",   "to": "SYNC"},
#       {"from": "SYNC",  "when": "locked_i",  "to": "RUN"},
#       {"from": "SYNC",  "when": "timeout_i", "to": "IDLE"},
#       {"from": "RUN",   "when": "stop_i",    "to": "FLUSH"},
#       {"from": "FLUSH", "when": "1'b1",      "to": "IDLE"}
#     ]
#   }
#
# Conditions are Verilog expressions over the module's inputs (every
# identifier ending in _i is collected into the port list). Priority is
# spec order within a state; no matching condition holds the state.
# The generated module exposes state_o, err_o and one input per used
# signal. If the state count is an exact power of two there is no
# unreachable encoding to trap - the generator widens the register by
# one bit rather than emit a trap-free FSM, and says so in the header.
# =============================================================================

import argparse
import json
import math
import re
import sys
from pathlib import Path

HEADER = """// GENERATED by scripts/tmr_fsm_gen.py - edit the spec, not this file.
//
// Safe-state TMR FSM '{name}': state in a voted-feedback TMR register
// (zirh_tmr_lib), single-replica upsets heal in one cycle and pulse
// err_o; the {ntrap} unreachable encoding(s) of the {width}-bit state
// space fall into {recovery} through the case default - the trap a
// double-replica hit needs.{widen_note}
"""


def generate(spec):
    name = spec["name"]
    states = spec["states"]
    recovery = spec["recovery"]
    if recovery not in states:
        sys.exit(f"recovery state {recovery} is not in states")
    n = len(states)
    width = max(1, math.ceil(math.log2(n)))
    widen_note = ""
    if (1 << width) == n:
        width += 1
        widen_note = ("\n// NOTE: state count is a power of two; the "
                      "register is widened one bit so a trap exists.")
    ntrap = (1 << width) - n

    inputs = []
    for t in spec["transitions"]:
        for tok in re.findall(r"[A-Za-z_][A-Za-z0-9_]*", t["when"]):
            if tok.endswith("_i") and tok not in inputs:
                inputs.append(tok)

    enc = {s: f"{width}'d{i}" for i, s in enumerate(states)}
    lines = []
    add = lines.append
    add(HEADER.format(name=name, ntrap=ntrap, width=width,
                      recovery=recovery, widen_note=widen_note))
    add("`default_nettype none")
    add("")
    add(f"module {name} (")
    add("    input  wire clk,")
    add("    input  wire rst_n,")
    for p in inputs:
        add(f"    input  wire {p},")
    add(f"    output wire [{width - 1}:0] state_o,")
    add("    output wire err_o")
    add(");")
    add("")
    for s in states:
        add(f"    localparam [{width - 1}:0] S_{s} = {enc[s]};")
    add("")
    add(f"    wire [{width - 1}:0] state_q;")
    add(f"    reg  [{width - 1}:0] state_d;")
    add("")
    add(f"    zirh_tmr_reg #(.WIDTH({width})) u_state (")
    add("        .clk(clk), .rst_n(rst_n), .en_i(1'b1), .d_i(state_d),")
    add("        .q_o(state_q), .err_o(err_o));")
    add("")
    add("    always @(*) begin")
    add("        case (state_q)")
    for s in states:
        ts = [t for t in spec["transitions"] if t["from"] == s]
        if not ts:
            add(f"            S_{s}: state_d = S_{s};")
            continue
        expr = f"S_{s}"
        for t in reversed(ts):
            expr = f"({t['when']}) ? S_{t['to']} : {expr}"
        add(f"            S_{s}: state_d = {expr};")
    add(f"            default: state_d = S_{recovery};"
        "   // the safe-state trap")
    add("        endcase")
    add("    end")
    add("")
    add("    assign state_o = state_q;")
    add("")
    add("endmodule")
    add("")
    add("`default_nettype wire")
    add("")
    verilog = "\n".join(lines)

    # proof obligations: one zirh_tmr_reg -> 3 replica cells of ONE
    # paramod definition; flops = width x 3 replicas + 1 err flop
    manifest = {
        "name": name,
        "top": name,
        "sources": ["zirh_tmr_lib.v", f"{name}.v"],
        "expect_instances": 3,
        "expect_ffs": width * 3 + 1,
    }
    return verilog, manifest


def main():
    ap = argparse.ArgumentParser(description="safe-state TMR FSM generator")
    ap.add_argument("spec")
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("--manifest-entry",
                    help="write the tmr-guard check entry here")
    args = ap.parse_args()

    spec = json.loads(Path(args.spec).read_text())
    verilog, manifest = generate(spec)
    Path(args.out).write_text(verilog)
    print(f"generated {args.out}: {len(spec['states'])} states, "
          f"trap -> {spec['recovery']}, expect "
          f"{manifest['expect_instances']} replicas / "
          f"{manifest['expect_ffs']} flops")
    if args.manifest_entry:
        Path(args.manifest_entry).write_text(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
